### ISSUE TITLE
Optimise the REST command

### ISSUE THREAD

**Issue by GLVasseur** [ccl0utier/SA-DetectionInsight#16]
Hi there,

| rest splunk_server=local count=0 add_orphan_field=yes /services/saved/searches

In my environment this returns a table with 3600 rows and a ridiculous 1500 columns, so quite bad for memory usage. I ran in the same problem when developing my ConfManager app: https://splunkbase.splunk.com/app/6895 and discovered the f parameter. I eventually settled on:

| rest splunk_server=local count=0 /servicesNS/-/-/saved/searches f=author f=cron_schedule f=description f=disabled f=dispatch.earliest_time f=dispatch.latest_time f=is_scheduled f=is_visible f=search f=title f=updated f=eai:acl
    f=action.action_history
    f=action.correlationsearch
    f=action.correlationsearch.enabled
    f=action.customsearchbuilder
    f=action.email
    f=action.escu
    f=action.escu_contextualize
    f=action.escu_investigate
    f=action.keyindicator
    f=action.lookup
    f=action.notable
    f=action.output_message
    f=action.outputtelemetry
    f=action.populate_lookup
    f=action.risk
    f=action.rss
    f=action.script
    f=action.send2ba_notable
    f=action.send2ba_riskdm
    f=action.send2uba
    f=action.send_events_to_mc_action
    f=action.send_notable_to_mc_alert_action
    f=action.ssg_mobile_alert
    f=action.summary_index
    f=action.swimlane
    f=action.threat_activity
    f=action.threat_outputlookup

Which is at least twice as fast. Of course for your application you might need to refine the list of fields you need.

Hope this helps.

Quick question: do you have an ETA on a release on splunkbase? We're in cloud and I'd rather install apps via splunkbase where possible.

Cheers,
Gabriel.

**Comment by ccl0utier** [comment]
Bonjour @GLVasseur,

Merci beaucoup pour l'astuce! J'ajoute cette amélioration à la prochaine version en cours.

"Learn something new every day" 👍🏼 

Regarding Splunkbase, that's something I'm trying to expedite, given I've opened the request for that a few months back (the initial process is a little more involved for Splunkers).

**Comment by ccl0utier** [comment]
Closed as part of v1.0.3.
